### ISSUE TITLE
handler_worker:ERROR:Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by awindsr** [monkeydluffy7/blackpearl-bbcode-bot#1]
Traceback (most recent call last):                                                                                       
 File "\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 217, in handler_worker                                                                                                                
await handler.callback(self.client, *args)                                                                            
File "\blackpearl-bbcode-bot-main\BPBBCODE.py", line 389, in BPMV       Language = getLANG(MOVIE_PATH)                                                                                        
File "\blackpearl-bbcode-bot-main\BPBBCODE.py", line 232, in getLANG                                                                                                                            mediainfo = json.load(mediainfo_output.stdout)                                                                        
File "\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load                      
return loads(fp.read(),                                                                                               
File "\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads                     
return _default_decoder.decode(s)                                                                                    
 File "\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode                     
obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                     
File "\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode                 
raise JSONDecodeError("Expecting value", s, err.value) from None                                                    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by monkeydluffy7** [comment]
Have you put mediainfo binary in same path?
